spring.application.name=Curso con SpringBoot

server.servlet.context-path=/sistema/api/v1
server.port=8080

service.products=list


#externalización de configuraciones 
#Configuración personalizada de la aplicación
#app --> puede ser lo que se, pero por buenas prácticas es app
app.name=Sistema de productos
app.version=1.0.0
app.autor=Desarrollos inovadores S.A.
app.language=es
app.country=Mexico